//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.18 at 06:14:35 PM CST 
//


package org.astm.ccr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProblemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProblemType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:astm-org:CCR}CCRCodedDataObjectType">
 *       &lt;sequence>
 *         &lt;element name="Episodes" type="{urn:astm-org:CCR}EpisodesType" minOccurs="0"/>
 *         &lt;element name="HealthStatus" type="{urn:astm-org:CCR}CurrentHealthStatusType" minOccurs="0"/>
 *         &lt;element name="PatientKnowledge" type="{urn:astm-org:CCR}PatientKnowledgeType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProblemType", propOrder = {
    "episodes",
    "healthStatus",
    "patientKnowledge"
})
public class ProblemType
    extends CCRCodedDataObjectType
{

    @XmlElement(name = "Episodes")
    protected EpisodesType episodes;
    @XmlElement(name = "HealthStatus")
    protected CurrentHealthStatusType healthStatus;
    @XmlElement(name = "PatientKnowledge")
    protected PatientKnowledgeType patientKnowledge;

    /**
     * Gets the value of the episodes property.
     * 
     * @return
     *     possible object is
     *     {@link EpisodesType }
     *     
     */
    public EpisodesType getEpisodes() {
        return episodes;
    }

    /**
     * Sets the value of the episodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EpisodesType }
     *     
     */
    public void setEpisodes(EpisodesType value) {
        this.episodes = value;
    }

    /**
     * Gets the value of the healthStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentHealthStatusType }
     *     
     */
    public CurrentHealthStatusType getHealthStatus() {
        return healthStatus;
    }

    /**
     * Sets the value of the healthStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentHealthStatusType }
     *     
     */
    public void setHealthStatus(CurrentHealthStatusType value) {
        this.healthStatus = value;
    }

    /**
     * Gets the value of the patientKnowledge property.
     * 
     * @return
     *     possible object is
     *     {@link PatientKnowledgeType }
     *     
     */
    public PatientKnowledgeType getPatientKnowledge() {
        return patientKnowledge;
    }

    /**
     * Sets the value of the patientKnowledge property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientKnowledgeType }
     *     
     */
    public void setPatientKnowledge(PatientKnowledgeType value) {
        this.patientKnowledge = value;
    }

}
