//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.18 at 06:14:35 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:astm-org:CCR", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.astm.ccr;
